# Generated by Django 2.2.7 on 2019-11-21 19:19

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('imgfile', imagekit.models.fields.ProcessedImageField(upload_to='blog/post')),
            ],
        ),
    ]
